server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: squid
    static_configs:
      - targets:
          - localhost
        labels:
          job: squid
          __path__: /var/log/squid/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<client_ip>\S+) (?P<status_code>[A-Z_]+)\/(?P<http_status>\d+) (?P<response_time>\d+) (?P<method>[A-Za-z\\-]+) (?P<url>.+)$'
      - labels:
          client_ip:
          method:
          http_status:
          status_code:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: 'Asia/Dhaka'
